// rdc-client-angular/src/app/pages/session/observer/observer.component.ts
import { Component, ElementRef, HostListener, Input, AfterViewInit, ViewChild } from '@angular/core';
import { EnginesService } from 'src/app/service/engines/engines.service';

@Component({
  selector: 'app-observer',
  templateUrl: './observer.component.html',
  styleUrls: ['./observer.component.css'],
})
export class ObserverComponent implements AfterViewInit {
  @Input('userId')
  userId!: string;

  @Input('streamId')
  streamId!: number;

  isFullscreen: boolean = false;

  @ViewChild('attachEl')
  attachRef!: ElementRef<HTMLInputElement>;

  width: string = `${window.innerWidth}px`;
  height: string = `${window.innerHeight - 56}px`;

  constructor(private enginesService: EnginesService) {}

  ngAfterViewInit(): void {
    const { rdcEngine } = this.enginesService;
    if (!rdcEngine) {
      return;
    }
    rdcEngine.observe(this.userId, this.streamId, this.attachRef.nativeElement);
  }

  @HostListener('window:resize', ['$event'])
  handleResize(event: any) {
    this.height = `${event.target.innerHeight - 56}px`;
    this.width = `${event.target.innerWidth}px`;
  }

}

<div class="rdc-client-screen-wrap">
    <div class="rdc-screen" [ngStyle]="{height: height, width: width}" #attachEl>
    </div>
</div>

// rdc-client/src/pages/Session/Observer.tsx
import React, { FC, useCallback, useEffect, useRef, useState } from 'react';
import { useThrottleFn } from 'react-use';
import { useEngines } from '../../hooks/engines';

export interface ObserverProps {
  userId: string;
  streamId: number;
}

export const Observer: FC<ObserverProps> = ({ streamId, userId }) => {
  const { rdcEngine } = useEngines();
  const attachRef = useRef<HTMLDivElement>(null);
  const [[width, height], setSize] = useState<[number, number]>([window.innerWidth, window.innerHeight - 56]);
  const size = useThrottleFn<[number, number], [number, number]>((w, h) => [w, h], 100, [width, height]);
  const handleResize = useCallback(() => setSize([window.innerWidth, window.innerHeight - 56]), [setSize]);

  useEffect(() => {
    if (rdcEngine && attachRef && attachRef.current) {
      rdcEngine.observe(userId, streamId, attachRef.current);
    }
  }, [streamId, rdcEngine, attachRef]);

  useEffect(() => {
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, [handleResize]);

  return (
    <div className="rdc-client-screen-wrap">
      <div className="rdc-screen" ref={attachRef} style={size ? { width: size[0], height: size[1] } : undefined} />
    </div>
  );
};
