// rdc-client-angular/src/app/pages/session/controlled/controlled.component.ts
import { Component, OnInit, TemplateRef, ViewChild } from '@angular/core';
import { NzMessageService } from 'ng-zorro-antd/message';
import { RDCDisplay, RDCDisplayConfiguration, RDCRoleType } from 'agora-rdc-core';
import { ActivatedRoute } from '@angular/router';
import { EnginesService } from '../../../service/engines/engines.service';
import { ParametersService } from '../../../service/parameters/parameters.service';
import { Profile } from '../../../service/api/api.service';
import { ControlledOptions } from '../../../interfaces';
import { RESOLUTION_BITRATE } from '../../../constants';
import { ProfilesService } from 'src/app/service/profile/profiles.service';
import { NzModalService } from 'ng-zorro-antd/modal';

@Component({
  selector: 'app-controlled',
  templateUrl: './controlled.component.html',
  styleUrls: ['./controlled.component.css'],
})
export class ControlledComponent implements OnInit {
  userIdsUnderObserving: string[] = [];
  userIdControlledBy?: string;
  displays: RDCDisplay[] = [];
  visible: boolean = false;
  profiles: Profile[] = [];
  rdcDisplayConfiguration?: Partial<RDCDisplayConfiguration>;

  get profilesUnderObserving() {
    return this.profiles.filter((profile) => this.userIdsUnderObserving.includes(profile.userId));
  }

  @ViewChild('warnMessageTemplate', { read: TemplateRef })
  warnMessageTemplate!: TemplateRef<any>;

  get controlledByProfile() {
    const profile = this.profiles.find((profile) => profile.userId === this.userIdControlledBy);
    return profile;
  }

  get RDCRoleType() {
    return RDCRoleType;
  }

  constructor(
    private activatedRoute: ActivatedRoute,
    private parameterService: ParametersService,
    private enginesService: EnginesService,
    private profilesService: ProfilesService,
    private messageService: NzMessageService,
    private modalService: NzModalService,
  ) {}

  ngOnInit(): void {
    this.parameterService
      .getOptions<ControlledOptions>(this.activatedRoute)
      .then((options) => this.parseOptions(options));
    this.profilesService.profiles.subscribe((profiles) => (this.profiles = profiles));
    const { rdcEngine } = this.enginesService;
    if (!rdcEngine) {
      return;
    }
    rdcEngine.on('rdc-request-control', this.handleRequestControl);
    rdcEngine.on('rdc-quit-control', this.handleQuitControl);
  }

  handleObserve(profile: Profile) {
    this.userIdsUnderObserving = [...this.userIdsUnderObserving, profile.userId];
  }

  handleUnobserve(profile?: Profile) {
    const { rdcEngine } = this.enginesService;
    if (!rdcEngine || !profile) {
      return;
    }
    rdcEngine.unobserve(profile.userId, profile.screenStreamId);
    this.userIdsUnderObserving = this.userIdsUnderObserving.filter((id) => id !== profile.userId);
  }

  handleAuthorize(display: RDCDisplay) {
    const profile = this.profiles.find((profile) => profile.userId === this.userIdControlledBy);
    const { rdcEngine } = this.enginesService;
    const { userIdControlledBy } = this;
    if (!userIdControlledBy || !rdcEngine || !profile) {
      return;
    }
    rdcEngine.authorizeControl(userIdControlledBy, display, this.rdcDisplayConfiguration, true);
    this.visible = false;
    this.messageService.warning(this.warnMessageTemplate, { nzDuration: 0 });
  }

  declineRequest() {
    const { rdcEngine } = this.enginesService;
    if (!rdcEngine) {
      return;
    }
    const profile = this.profiles.find((profile) => {
      return profile.userId === this.userIdControlledBy;
    });
    if (!profile) {
      return;
    }
    this.visible = false;
    rdcEngine.unauthorizeControl(profile.userId);
    this.messageService.info(`You have been declined control request from ${profile.name}`);
    this.userIdControlledBy = undefined;
  }

  doubleConfirm(profile?: Profile) {
    if (!profile) {
      return;
    }
    this.modalService.confirm({
      nzTitle: 'Are you sure to quit control?',
      nzContent: `${profile.name} will not be able to control your computer anymore.`,
      nzOkText: 'Yes',
      nzCancelText: 'No',
      nzOnOk: () => {
        this.handleStopControl();
      },
    });
  }
  handleStopControl() {
    const profile = this.profiles.find((profile) => profile.userId === this.userIdControlledBy);
    const { rdcEngine } = this.enginesService;
    if (!rdcEngine || !profile) {
      return;
    }

    rdcEngine.quitControl(profile.userId, profile.rdcRole);
    this.messageService.remove();
    this.messageService.info(`You have stopped control by ${profile.name}.`);
    this.userIdControlledBy = undefined;
  }

  private handleRequestControl = async (userId: string) => {
    const { rdcEngine } = this.enginesService;
    if (!rdcEngine) {
      return;
    }
    this.displays = await rdcEngine.getDisplays();
    this.userIdControlledBy = userId;
    this.visible = true;
  };

  private handleQuitControl = (userId: string) => {
    const { rdcEngine } = this.enginesService;
    const { userIdControlledBy } = this;
    if (!rdcEngine || !userIdControlledBy) {
      return;
    }
    const profile = this.profiles.find((p) => p.userId === userId);
    if (!profile) {
      return;
    }
    rdcEngine.quitControl(userId, profile.rdcRole);
    this.messageService.remove();
    this.messageService.info(`${profile.name} is released control.`);
    this.userIdControlledBy = undefined;
  };

  private parseOptions(options: ControlledOptions) {
    const { resolutionBitrate, frameRate } = options;
    const configuration: Partial<RDCDisplayConfiguration> = { frameRate };
    if (resolutionBitrate) {
      const { width, height, bitrate } = RESOLUTION_BITRATE[resolutionBitrate];
      configuration.width = width;
      configuration.height = height;
      configuration.bitrate = bitrate;
    }
    this.rdcDisplayConfiguration = configuration;
  }
}

<app-profiles>
	<ng-template #action let-profile>
		<nz-tag *ngIf="profile.rdcRole === RDCRoleType.HOST" nzColor="gold">HOST</nz-tag>
		<span *ngIf="profile.rdcRole === RDCRoleType.CONTROLLED">
			<button nz-button nzType="link" (click)="handleObserve(profile)"
				[disabled]="userIdsUnderObserving.includes(profile.userId)">Start Observation</button>
			<button nz-button nzType="link" (click)="handleUnobserve(profile)"
				[disabled]="!userIdsUnderObserving.includes(profile.userId)">Stop Observation</button>
		</span>
	</ng-template>
</app-profiles>
<nz-tabset [nzTabBarStyle]="{margin: '0px'}">
	<nz-tab *ngFor="let profile of profilesUnderObserving" [nzTitle]="profile.name">
		<app-observer [userId]="profile.userId" [streamId]="profile.screenStreamId"></app-observer>
	</nz-tab>
</nz-tabset>
<nz-modal nzTitle="Please click the screen which you want to authorize." [nzVisible]="visible" [nzFooter]="null"
	(nzOnCancel)="declineRequest()" [nzBodyStyle]="{padding: '0px'}">
	<ng-container *nzModalContent>
		<nz-tabset>
			<nz-tab *ngFor="let display of displays" [nzTitle]="display.height + ' x ' + display.width">
				<div style="height: 100%; width: 100%; cursor: pointer" (click)="handleAuthorize(display)">
					<img style="max-height: 100%; max-width: 100%" [src]="display.thumbnail" alt="display" />
				</div>
			</nz-tab>
		</nz-tabset>
	</ng-container>
</nz-modal>
<ng-template #warnMessageTemplate>
	<span>Your computer is controlled by {{controlledByProfile?.name}}. </span>
	<span>
		<button nz-button nzType="link" nzDanger (click)="doubleConfirm(controlledByProfile)">
			<i nz-icon nzType="poweroff" nzTheme="outline" style="color: red;"></i>
		</button>
	</span>
</ng-template>

// rdc-client-vue/src/pages/Session/Controlled.vue
<script lang="ts" setup>
import { ref, watch, h, shallowRef } from 'vue';
import { RDCRoleType, RDCDisplay } from 'agora-rdc-core';
import { message, Modal } from 'ant-design-vue';
import { PoweroffOutlined } from '@ant-design/icons-vue';
import { useSession } from '../../hooks/session';
import { useEngines } from '../../hooks/engines';
import { useProfiles } from '../../hooks/profiles';
import { useRDCDisplayConfiguration } from '../../hooks/options';
import Profiles from './Profiles.vue';
import { Profile } from '../../api';
import Observer from './Observer.vue';

const session = useSession();
const engines = ref(useEngines());
const profiles = useProfiles();
const rdcDisplayConfiguration = useRDCDisplayConfiguration();
const userIdsUnderObserving = ref<string[]>([]);
const visible = ref(false);
const activeKey = ref<string>();
const displays = shallowRef<RDCDisplay[]>([]);
const userIdControlledBy = ref<string>();

const handleObserve = (userId: string) => {
  userIdsUnderObserving.value = [...userIdsUnderObserving.value, userId];
};

const handleUnobserve = (userId: string, streamId: number) => {
  engines.value?.rdcEngine.unobserve(userId, streamId);
  userIdsUnderObserving.value = userIdsUnderObserving.value.filter((id) => id !== userId);
};

const handleRequestControl = async (userId: string) => {
  if (!engines.value) {
    return;
  }
  displays.value = await engines.value.rdcEngine.getDisplays();
  userIdControlledBy.value = userId;
  visible.value = true;
};

const handleQuitControl = (userId: string) => {
  if (!engines.value || !profiles.value || userIdControlledBy.value !== userId) {
    return;
  }
  const profile = profiles.value.find((p) => p.userId === userId);
  if (!profile) {
    return;
  }
  engines.value.rdcEngine.quitControl(userId, profile.rdcRole);
  message.destroy();
  message.info(`${profile.name} is released control.`);
  userIdControlledBy.value = undefined;
};

const declineRequest = () => {
  const profile = profiles.value?.find((profile) => {
    return profile.userId === userIdControlledBy.value;
  });
  if (!profile) {
    return;
  }
  visible.value = false;
  engines.value?.rdcEngine.unauthorizeControl(profile.userId);
  message.info(`You have been declined control request from ${profile.name}`);
  userIdControlledBy.value = undefined;
};

const handleAuthorize = (display: RDCDisplay) => {
  const profile = profiles.value?.find((profile) => profile.userId === userIdControlledBy.value);
  if (!userIdControlledBy.value || !engines.value || !profile) {
    return;
  }

  engines.value.rdcEngine.authorizeControl(userIdControlledBy.value, display, rdcDisplayConfiguration, true);
  visible.value = false;
  message.warn(
    h('span', {}, [
      h('span', {}, `Your computer is controlled by ${profile.name}.`),
      h(
        'a-button',
        {
          type: 'link',
          style: { marginLeft: '10px' },
          danger: true,
          onClick: () => doubleConfirm(profile),
        },
        h(PoweroffOutlined, { style: { color: 'red' } }),
      ),
    ]),
    0,
  );
};

const doubleConfirm = (profile: Profile) => {
  Modal.confirm({
    title: 'Are you sure to quit control?',
    content: `${profile.name} will not be able to control your computer anymore.`,
    okText: 'Yes',
    cancelText: 'No',
    onOk: () => {
      userIdControlledBy.value && handleQuitControl(userIdControlledBy.value);
    },
  });
};

watch([engines], () => {
  if (!engines.value) {
    return;
  }
  engines.value.rdcEngine.on('rdc-request-control', handleRequestControl);
  engines.value.rdcEngine.on('rdc-quit-control', handleQuitControl);
});
</script>

<template>
  <div v-if="session?.rdcRole === RDCRoleType.CONTROLLED">
    <a-tabs>
      <a-tab-pane
        v-for="profile of profiles?.filter((p) => userIdsUnderObserving.includes(p.userId))"
        :key="`${profile.userId}`"
        :tab="profile.name"
      >
        <Observer :userId="profile.userId" :streamId="profile.screenStreamId" />
      </a-tab-pane>
    </a-tabs>
    <Profiles>
      <template #action="{ profile }">
        <a-tag v-if="profile.rdcRole === RDCRoleType.HOST" color="gold">HOST</a-tag>
        <span v-if="profile.rdcRole === RDCRoleType.CONTROLLED">
          <a-button
            type="link"
            @click="handleObserve(profile.userId)"
            :disabled="userIdsUnderObserving.includes(profile.userId)"
            >Start Observation</a-button
          >
          <a-divider type="vertical" />
          <a-button
            type="link"
            @click="handleUnobserve(profile.userId, profile.streamId)"
            :disabled="!userIdsUnderObserving.includes(profile.userId)"
            >Stop Observation</a-button
          >
        </span>
      </template>
    </Profiles>
    <a-modal
      title="Please click the screen which you want to authorize."
      :visible="visible"
      :footer="null"
      @cancel="declineRequest"
      :bodyStyle="{ padding: '8px' }"
    >
      <a-tabs v-model:activeKey="activeKey">
        <a-tab-pane
          v-for="(display, index) of displays"
          :tab="`Display: ${display.width} x ${display.height}`"
          :key="index"
        >
          <div style="height: 100%; width: 100%; cursor: pointer" @click="handleAuthorize(display)">
            <img style="max-height: 100%; max-width: 100%" :src="display.thumbnail" alt="display" />
          </div>
        </a-tab-pane>
      </a-tabs>
    </a-modal>
  </div>
</template>
