// rdc-client-angular/src/app/pages/session/host/host.component.ts
import { Component, OnInit } from '@angular/core';
import { NzMessageService } from 'ng-zorro-antd/message';
import { RDCRemotelyPastingStatus, RDCRemotelyPastingCodes } from 'agora-rdc-core';
import { ProfilesService } from '../../../service/profile/profiles.service';
import { Profile } from '../../../service/api/api.service';
import { EnginesService, RDCEngine } from '../../../service/engines/engines.service';

const PASTE_REMOTELY_REASON: { [k: number]: string } = {
  [RDCRemotelyPastingCodes.CONCURRENCY_LIMIT_EXCEEDED]: 'concurrency limit exceeded.',
  [RDCRemotelyPastingCodes.SIZE_OVERFLOW]: 'max file size is 30MB.',
  [RDCRemotelyPastingCodes.TIMEOUT]: 'transmission timeout.',
  [RDCRemotelyPastingCodes.UNSUPPORTED_FILE_TYPE]: 'pasting folder is not supported.',
};

@Component({
  selector: 'app-host',
  templateUrl: './host.component.html',
  styleUrls: ['./host.component.css'],
})
export class HostComponent implements OnInit {
  profiles: Profile[] = [];
  userIdsUnderControl: string[] = [];
  pasting: boolean = false;

  get profilesUnderControl() {
    return this.profiles.filter((p) => this.userIdsUnderControl.includes(p.userId));
  }

  constructor(
    private enginesService: EnginesService,
    private profilesService: ProfilesService,
    private messageService: NzMessageService,
  ) {}

  ngOnInit(): void {
    this.profilesService.profiles.subscribe((profiles) => {
      this.profiles = profiles;
    });
    this.bindRDCEvents();
  }

  handleRequestControl(profile: Profile) {
    this.enginesService.rdcEngine?.requestControl(profile.userId);
    this.messageService.success(`Control request has been sent to ${name}.`);
  }

  handleQuitControl(profile: Profile) {
    const { rdcEngine } = this.enginesService;
    if (!rdcEngine) {
      return;
    }
    rdcEngine.quitControl(profile.userId, profile.rdcRole, profile.screenStreamId);
  }

  private bindRDCEvents() {
    const { rdcEngine } = this.enginesService;
    if (!rdcEngine) {
      return;
    }
    rdcEngine.on('rdc-request-control-authorized', this.handleRequestControlAuthorized);
    rdcEngine.on('rdc-request-control-unauthorized', this.handleRequestControlUnauthorized);
    rdcEngine.on('rdc-quit-control', this.handleQuitControlEvent);
    rdcEngine.on('rdc-remote-paste', this.handleRemotePaste);
  }

  private handleRequestControlAuthorized = (userId: string) => {
    this.userIdsUnderControl = [...this.userIdsUnderControl, userId];
  };

  private handleRequestControlUnauthorized = (userId: string) => {
    const profile = this.profiles.find((p) => p.userId === userId);
    if (profile) {
      this.messageService.warning(`${profile.name} is declined your request`);
    }
  };

  private handleQuitControlEvent = (userId: string) => {
    this.userIdsUnderControl = this.userIdsUnderControl.filter((userIdUC) => userIdUC !== userId);
  };

  private handleRemotePaste = (status: RDCRemotelyPastingStatus, code: RDCRemotelyPastingCodes) => {
    if (status === RDCRemotelyPastingStatus.STARTING && code === RDCRemotelyPastingCodes.SUCCEEDED) {
      this.pasting = true;
      return;
    }

    if (status === RDCRemotelyPastingStatus.SUCCEEDED && code === RDCRemotelyPastingCodes.SUCCEEDED) {
      this.pasting = false;
      this.messageService.success('File is pasted.');
      return;
    }

    if (status === RDCRemotelyPastingStatus.FAILED) {
      this.messageService.error(`Failed to pasting file, cause ${PASTE_REMOTELY_REASON[code as number]}`);
      this.pasting = false;
      return;
    }
  };
}

<ng-template #indicatorTemplate><i nz-icon nzType="loading"></i></ng-template>

<nz-tabset [nzTabBarStyle]="{margin: '0px'}">
  <nz-tab *ngFor="let profile of profilesUnderControl" [nzTitle]="profile.name">
    <nz-spin [nzSpinning]="pasting" [nzIndicator]="indicatorTemplate" nzTip="File is pasting...">
      <app-controller [userId]="profile.userId" [streamId]="profile.screenStreamId"></app-controller>
    </nz-spin>
  </nz-tab>
</nz-tabset>
<app-profiles>
  <ng-template #action let-profile>
    <button nz-button nzType="link" (click)="handleRequestControl(profile)"
      [disabled]="userIdsUnderControl.includes(profile.userId)">Request Control</button>
    <button nz-button nzType="link" (click)="handleQuitControl(profile)"
      [disabled]="!userIdsUnderControl.includes(profile.userId)">Quit Control</button>
  </ng-template>
</app-profiles>

// rdc-client-vue/src/pages/Session/Host.vue
<script lang="ts" setup>
import { ref, watch, onBeforeUnmount, onMounted, h } from 'vue';
import { message } from 'ant-design-vue';
import { LoadingOutlined } from '@ant-design/icons-vue';
import { RDCRemotelyPastingCodes, RDCRemotelyPastingStatus, RDCRoleType } from 'agora-rdc-core';
import { Profile } from '../../api';
import { useSession } from '../../hooks/session';
import { useEngines } from '../../hooks/engines';
import { useProfiles } from '../../hooks/profiles';
import Profiles from './Profiles.vue';
import Controller from './Controller.vue';

const PASTE_REMOTELY_REASON: { [k: number]: string } = {
  [RDCRemotelyPastingCodes.CONCURRENCY_LIMIT_EXCEEDED]: 'concurrency limit exceeded.',
  [RDCRemotelyPastingCodes.SIZE_OVERFLOW]: 'max file size is 30MB.',
  [RDCRemotelyPastingCodes.TIMEOUT]: 'transmission timeout.',
  [RDCRemotelyPastingCodes.UNSUPPORTED_FILE_TYPE]: 'pasting folder is not supported.',
};

const session = useSession();
const engines = ref(useEngines());
const profiles = useProfiles();
const userIdsUnderControl = ref<string[]>([]);
const pasting = ref(false);

const indicator = h(LoadingOutlined, {
  style: {
    fontSize: '24px',
  },
  spin: true,
});

const handleRequestControlAuthorized = (userId: string) => {
  userIdsUnderControl.value = [...userIdsUnderControl.value, userId];
};

const handleRequestControlUnauthorized = (userId: string) => {
  const profile = profiles.value?.find((p) => p.userId === userId);
  if (profile) {
    message.warn(`${profile.name} is declined your request`);
  }
};

const handleQuitControlEvent = (userId: string) => {
  userIdsUnderControl.value = userIdsUnderControl.value.filter((userIdUC) => userIdUC !== userId);
};

const handleRemotePaste = (status: RDCRemotelyPastingStatus, code: RDCRemotelyPastingCodes) => {
  if (status === RDCRemotelyPastingStatus.STARTING && code === RDCRemotelyPastingCodes.SUCCEEDED) {
    pasting.value = true;
    return;
  }

  if (status === RDCRemotelyPastingStatus.SUCCEEDED && code === RDCRemotelyPastingCodes.SUCCEEDED) {
    pasting.value = false;
    message.success('File is pasted.');
    return;
  }

  if (status === RDCRemotelyPastingStatus.FAILED) {
    message.error(`Failed to pasting file, cause ${PASTE_REMOTELY_REASON[code as number]}`);
    pasting.value = false;
    return;
  }
};

const handleRequestControl = (profile: Profile) => {
  engines.value?.rdcEngine.requestControl(profile.userId);
  message.success(`Control request has been sent to ${name}.`);
};

const handleQuitControl = (profile: Profile) => {
  engines.value?.rdcEngine.quitControl(profile.userId, profile.rdcRole, profile.screenStreamId);
};

const handleBeforeunload = () => {
  profiles.value
    ?.filter((p) => userIdsUnderControl.value.includes(p.userId))
    .forEach(({ userId, rdcRole }) => engines.value?.rdcEngine.quitControl(userId, rdcRole));
  engines.value?.rdcEngine.leave();
  engines.value?.rdcEngine.dispose();
};

watch([engines], () => {
  if (!engines.value) {
    return;
  }
  engines.value.rdcEngine.on('rdc-request-control-authorized', handleRequestControlAuthorized);
  engines.value.rdcEngine.on('rdc-request-control-unauthorized', handleRequestControlUnauthorized);
  engines.value.rdcEngine.on('rdc-quit-control', handleQuitControlEvent);
  engines.value.rdcEngine.on('rdc-remote-paste', handleRemotePaste);
});

onMounted(() => {
  window.addEventListener('beforeunload', handleBeforeunload);
});
onBeforeUnmount(() => {
  if (!engines.value) {
    return;
  }
  engines.value.rdcEngine.off('rdc-request-control-authorized', handleRequestControlAuthorized);
  engines.value.rdcEngine.off('rdc-request-control-unauthorized', handleRequestControlUnauthorized);
  engines.value.rdcEngine.off('rdc-quit-control', handleQuitControlEvent);
  engines.value.rdcEngine.off('rdc-remote-paste', handleRemotePaste);
  handleBeforeunload();
  window.removeEventListener('beforeunload', handleBeforeunload);
});
</script>

<template>
  <div v-if="session?.rdcRole === RDCRoleType.HOST">
    <a-tabs>
      <a-tab-pane
        v-for="profile of profiles?.filter((p) => userIdsUnderControl.includes(p.userId))"
        :key="`${profile.userId}`"
        :tab="profile.name"
      >
        <a-spin :spinning="pasting" tip="File is pasting..." :indicator="indicator">
          <Controller :userId="profile.userId" :streamId="profile.screenStreamId" />
        </a-spin>
      </a-tab-pane>
    </a-tabs>
    <Profiles>
      <template #action="{ profile }">
        <a-button
          type="link"
          @click="handleRequestControl(profile)"
          :disabled="userIdsUnderControl.includes(profile.userId)"
          >Request Control</a-button
        >
        <a-divider type="vertical" />
        <a-button
          type="link"
          @click="handleQuitControl(profile)"
          :disabled="!userIdsUnderControl.includes(profile.userId)"
          >Quit Control</a-button
        >
      </template>
    </Profiles>
  </div>
</template>
