// rdc-client/src/pages/Session/Host.tsx
import React, { FC, useCallback, useEffect, useState } from 'react';
import { Button, Divider, List, message, Spin, Tabs } from 'antd';
import { LoadingOutlined } from '@ant-design/icons';
import { RDCRoleType, RDCRemotelyPastingCodes, RDCRemotelyPastingStatus } from 'agora-rdc-core';
import { Profile } from '../../api';
import { Profiles } from './Profiles';
import { useSession } from '../../hooks/session';
import { useEngines } from '../../hooks/engines';
import { useProfiles, useUserLeft } from '../../hooks/profiles';
import { Controller } from './Controller';

const PASTE_REMOTELY_REASON: { [k: number]: string } = {
  [RDCRemotelyPastingCodes.CONCURRENCY_LIMIT_EXCEEDED]: 'concurrency limit exceeded.',
  [RDCRemotelyPastingCodes.SIZE_OVERFLOW]: 'max file size is 30MB.',
  [RDCRemotelyPastingCodes.TIMEOUT]: 'transmission timeout.',
  [RDCRemotelyPastingCodes.UNSUPPORTED_FILE_TYPE]: 'pasting folder is not supported.',
};

export const Host: FC = () => {
  const session = useSession();
  const { rdcEngine } = useEngines();
  const profiles = useProfiles();
  const [userIdsUnderControl, setUserIdsUnderControl] = useState<string[]>([]);
  const [pasting, setPasting] = useState(false);

  const handleRequestControlAuthorized = useCallback(
    (userId: string) => setUserIdsUnderControl([...userIdsUnderControl, userId]),
    [userIdsUnderControl, setUserIdsUnderControl],
  );

  const handleRequestControlUnauthorized = useCallback(
    (userId: string) => {
      const profile = profiles.find((p) => p.userId === userId);
      if (profile) {
        message.warn(`${profile.name} is declined your request`);
      }
    },
    [profiles],
  );

  const handleQuitControlEvent = useCallback(
    (userId: string) => setUserIdsUnderControl(userIdsUnderControl.filter((userIdUC) => userIdUC !== userId)),
    [userIdsUnderControl, setUserIdsUnderControl],
  );

  const handleRemotePaste = useCallback((status: RDCRemotelyPastingStatus, code: RDCRemotelyPastingCodes) => {
    if (status === RDCRemotelyPastingStatus.STARTING && code === RDCRemotelyPastingCodes.SUCCEEDED) {
      setPasting(true);
      return;
    }

    if (status === RDCRemotelyPastingStatus.SUCCEEDED && code === RDCRemotelyPastingCodes.SUCCEEDED) {
      setPasting(false);
      message.success('File is pasted.');
      return;
    }

    if (status === RDCRemotelyPastingStatus.FAILED) {
      message.error(`Failed to pasting file, cause ${PASTE_REMOTELY_REASON[code as number]}`);
      setPasting(false);
      return;
    }
  }, []);

  const handleQuitControl = (userId: string, role: RDCRoleType, streamId: number) => {
    rdcEngine?.quitControl(userId, role, streamId);
  };

  const handleRequestControl = (userId: string, name: string) => {
    rdcEngine?.requestControl(userId);
    message.success(`Control request has been sent to ${name}.`);
  };

  const handleBeforeunload = useCallback(() => {
    if (!rdcEngine) {
      return;
    }
    profiles
      .filter((p) => userIdsUnderControl.includes(p.userId))
      .forEach(({ userId, rdcRole }) => rdcEngine.quitControl(userId, rdcRole));
    rdcEngine.leave();
    rdcEngine.dispose();
  }, [rdcEngine, userIdsUnderControl, profiles]);

  // Handle RDCEngine Events
  useEffect(() => {
    if (!rdcEngine) {
      return;
    }
    rdcEngine.on('rdc-request-control-authorized', handleRequestControlAuthorized);
    rdcEngine.on('rdc-request-control-unauthorized', handleRequestControlUnauthorized);
    rdcEngine.on('rdc-quit-control', handleQuitControlEvent);
    rdcEngine.on('rdc-remote-paste', handleRemotePaste);
    return () => {
      rdcEngine.off('rdc-request-control-authorized', handleRequestControlAuthorized);
      rdcEngine.off('rdc-request-control-unauthorized', handleRequestControlUnauthorized);
      rdcEngine.off('rdc-quit-control', handleQuitControlEvent);
      rdcEngine.off('rdc-remote-paste', handleRemotePaste);
    };
  }, [
    handleQuitControlEvent,
    handleRequestControlAuthorized,
    handleRequestControlUnauthorized,
    handleRemotePaste,
    rdcEngine,
  ]);

  useEffect(() => {
    window.addEventListener('beforeunload', handleBeforeunload);
    return () => window.removeEventListener('beforeunload', handleBeforeunload);
  }, [rdcEngine, handleBeforeunload]);

  // hack for controlled end destroy rdc engine too early.
  useUserLeft(handleQuitControlEvent);

  const renderItem = (profile: Profile) => (
    <List.Item>
      <div>
        <span style={{ marginRight: 10 }}>{profile.name}</span>
        <Button
          type="link"
          onClick={() => handleRequestControl(profile.userId, profile.name)}
          disabled={userIdsUnderControl.includes(profile.userId)}>
          Request Control
        </Button>
        <Divider type="vertical" />
        <Button
          type="link"
          onClick={() => handleQuitControl(profile.userId, profile.rdcRole, profile.screenStreamId)}
          disabled={!userIdsUnderControl.includes(profile.userId)}>
          Quit Control
        </Button>
      </div>
    </List.Item>
  );

  return session && session.rdcRole === RDCRoleType.HOST ? (
    <>
      <Tabs>
        {profiles
          .filter((profile) => userIdsUnderControl.includes(profile.userId))
          .map((profile) => (
            <Tabs.TabPane tab={profile.name} key={profile.userId} forceRender>
              <Spin
                spinning={pasting}
                tip="File is pasting..."
                indicator={<LoadingOutlined style={{ fontSize: 24 }} spin />}>
                <Controller userId={profile.userId} streamId={profile.screenStreamId} />
              </Spin>
            </Tabs.TabPane>
          ))}
      </Tabs>
      <Profiles renderItem={renderItem} />
    </>
  ) : null;
};

// rdc-client-vue/src/pages/Session/Host.vue
<script lang="ts" setup>
import { ref, watch, onBeforeUnmount, onMounted, h } from 'vue';
import { message } from 'ant-design-vue';
import { LoadingOutlined } from '@ant-design/icons-vue';
import { RDCRemotelyPastingCodes, RDCRemotelyPastingStatus, RDCRoleType } from 'agora-rdc-core';
import { Profile } from '../../api';
import { useSession } from '../../hooks/session';
import { useEngines } from '../../hooks/engines';
import { useProfiles } from '../../hooks/profiles';
import Profiles from './Profiles.vue';
import Controller from './Controller.vue';

const PASTE_REMOTELY_REASON: { [k: number]: string } = {
  [RDCRemotelyPastingCodes.CONCURRENCY_LIMIT_EXCEEDED]: 'concurrency limit exceeded.',
  [RDCRemotelyPastingCodes.SIZE_OVERFLOW]: 'max file size is 30MB.',
  [RDCRemotelyPastingCodes.TIMEOUT]: 'transmission timeout.',
  [RDCRemotelyPastingCodes.UNSUPPORTED_FILE_TYPE]: 'pasting folder is not supported.',
};

const session = useSession();
const engines = ref(useEngines());
const profiles = useProfiles();
const userIdsUnderControl = ref<string[]>([]);
const pasting = ref(false);

const indicator = h(LoadingOutlined, {
  style: {
    fontSize: '24px',
  },
  spin: true,
});

const handleRequestControlAuthorized = (userId: string) => {
  userIdsUnderControl.value = [...userIdsUnderControl.value, userId];
};

const handleRequestControlUnauthorized = (userId: string) => {
  const profile = profiles.value?.find((p) => p.userId === userId);
  if (profile) {
    message.warn(`${profile.name} is declined your request`);
  }
};

const handleQuitControlEvent = (userId: string) => {
  userIdsUnderControl.value = userIdsUnderControl.value.filter((userIdUC) => userIdUC !== userId);
};

const handleRemotePaste = (status: RDCRemotelyPastingStatus, code: RDCRemotelyPastingCodes) => {
  if (status === RDCRemotelyPastingStatus.STARTING && code === RDCRemotelyPastingCodes.SUCCEEDED) {
    pasting.value = true;
    return;
  }

  if (status === RDCRemotelyPastingStatus.SUCCEEDED && code === RDCRemotelyPastingCodes.SUCCEEDED) {
    pasting.value = false;
    message.success('File is pasted.');
    return;
  }

  if (status === RDCRemotelyPastingStatus.FAILED) {
    message.error(`Failed to pasting file, cause ${PASTE_REMOTELY_REASON[code as number]}`);
    pasting.value = false;
    return;
  }
};

const handleRequestControl = (profile: Profile) => {
  engines.value?.rdcEngine.requestControl(profile.userId);
  message.success(`Control request has been sent to ${name}.`);
};

const handleQuitControl = (profile: Profile) => {
  engines.value?.rdcEngine.quitControl(profile.userId, profile.rdcRole, profile.screenStreamId);
};

const handleBeforeunload = () => {
  profiles.value
    ?.filter((p) => userIdsUnderControl.value.includes(p.userId))
    .forEach(({ userId, rdcRole }) => engines.value?.rdcEngine.quitControl(userId, rdcRole));
  engines.value?.rdcEngine.leave();
  engines.value?.rdcEngine.dispose();
};

watch([engines], () => {
  if (!engines.value) {
    return;
  }
  engines.value.rdcEngine.on('rdc-request-control-authorized', handleRequestControlAuthorized);
  engines.value.rdcEngine.on('rdc-request-control-unauthorized', handleRequestControlUnauthorized);
  engines.value.rdcEngine.on('rdc-quit-control', handleQuitControlEvent);
  engines.value.rdcEngine.on('rdc-remote-paste', handleRemotePaste);
});

onMounted(() => {
  window.addEventListener('beforeunload', handleBeforeunload);
});
onBeforeUnmount(() => {
  if (!engines.value) {
    return;
  }
  engines.value.rdcEngine.off('rdc-request-control-authorized', handleRequestControlAuthorized);
  engines.value.rdcEngine.off('rdc-request-control-unauthorized', handleRequestControlUnauthorized);
  engines.value.rdcEngine.off('rdc-quit-control', handleQuitControlEvent);
  engines.value.rdcEngine.off('rdc-remote-paste', handleRemotePaste);
  handleBeforeunload();
  window.removeEventListener('beforeunload', handleBeforeunload);
});
</script>

<template>
  <div v-if="session?.rdcRole === RDCRoleType.HOST">
    <a-tabs>
      <a-tab-pane
        v-for="profile of profiles?.filter((p) => userIdsUnderControl.includes(p.userId))"
        :key="`${profile.userId}`"
        :tab="profile.name"
      >
        <a-spin :spinning="pasting" tip="File is pasting..." :indicator="indicator">
          <Controller :userId="profile.userId" :streamId="profile.screenStreamId" />
        </a-spin>
      </a-tab-pane>
    </a-tabs>
    <Profiles>
      <template #action="{ profile }">
        <a-button
          type="link"
          @click="handleRequestControl(profile)"
          :disabled="userIdsUnderControl.includes(profile.userId)"
          >Request Control</a-button
        >
        <a-divider type="vertical" />
        <a-button
          type="link"
          @click="handleQuitControl(profile)"
          :disabled="!userIdsUnderControl.includes(profile.userId)"
          >Quit Control</a-button
        >
      </template>
    </Profiles>
  </div>
</template>
