// rdc-client/src/pages/Session/Observer.tsx
import React, { FC, useCallback, useEffect, useRef, useState } from 'react';
import { useThrottleFn } from 'react-use';
import { useEngines } from '../../hooks/engines';

export interface ObserverProps {
  userId: string;
  streamId: number;
}

export const Observer: FC<ObserverProps> = ({ streamId, userId }) => {
  const { rdcEngine } = useEngines();
  const attachRef = useRef<HTMLDivElement>(null);
  const [[width, height], setSize] = useState<[number, number]>([window.innerWidth, window.innerHeight - 56]);
  const size = useThrottleFn<[number, number], [number, number]>((w, h) => [w, h], 100, [width, height]);
  const handleResize = useCallback(() => setSize([window.innerWidth, window.innerHeight - 56]), [setSize]);

  useEffect(() => {
    if (rdcEngine && attachRef && attachRef.current) {
      rdcEngine.observe(userId, streamId, attachRef.current);
    }
  }, [streamId, rdcEngine, attachRef]);

  useEffect(() => {
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, [handleResize]);

  return (
    <div className="rdc-client-screen-wrap">
      <div className="rdc-screen" ref={attachRef} style={size ? { width: size[0], height: size[1] } : undefined} />
    </div>
  );
};

// rdc-client-vue/src/pages/Session/Observer.vue
<script lang="ts" setup>
import { ref, watch, defineProps } from 'vue';
import { useWindowSize } from '@vueuse/core';
import { useEngines } from '../../hooks/engines';

const attachRef = ref<HTMLDivElement | null>(null);
const engines = ref(useEngines());
const props = defineProps<{
  userId: string;
  streamId: number;
}>();
const { width, height } = useWindowSize();

watch([engines, props, attachRef], () => {
  if (!engines.value || !attachRef.value) {
    return;
  }
  engines.value.rdcEngine.observe(props.userId, props.streamId, attachRef.value);
});
</script>

<template>
  <div className="rdc-client-screen-wrap">
    <div className="rdc-screen" ref="attachRef" :style="{ height: `${height - 56}px`, width: `${width}px` }" />
  </div>
</template>
