// rdc-client-vue/src/pages/Session/Profiles.vue
<script lang="ts" setup>
import { ref } from 'vue';
import { UserOutlined } from '@ant-design/icons-vue';
import { useProfiles } from '../../hooks/profiles';

const visible = ref(true);
const profiles = useProfiles();

const toggleVisible = () => {
  visible.value = !visible.value;
};
</script>
<template>
  <a-drawer
    :closable="false"
    :width="500"
    :placement="'right'"
    :mask-closable="true"
    :destroy-on-close="true"
    :visible="visible"
    @close="toggleVisible"
  >
    <a-list item-layout="horizontal" :data-source="profiles">
      <template #renderItem="{ item }">
        <a-list-item>
          <div>
            <span style="margin-right: 10px">{{ item.name }}</span>
            <slot name="action" :profile="item"></slot>
          </div>
        </a-list-item>
      </template>
    </a-list>
  </a-drawer>
  <a-affix style="position: absolute; right: 10px; bottom: 20px">
    <a-button type="primary" shape="circle" @click="toggleVisible">
      <template #icon><UserOutlined /></template>
    </a-button>
  </a-affix>
</template>

// rdc-client-angular/src/app/pages/session/profiles/profiles.component.ts
import { Component, ContentChild, OnInit, TemplateRef } from '@angular/core';
import { Profile } from '../../../service/api/api.service';
import { ProfilesService } from '../../../service/profile/profiles.service';

@Component({
  selector: 'app-profiles',
  templateUrl: './profiles.component.html',
  styleUrls: ['./profiles.component.css'],
})
export class ProfilesComponent implements OnInit {
  visible = true;
  profiles: Profile[] = [];

  @ContentChild('action')
  actionTemplate!: TemplateRef<any>;

  constructor(private profilesService: ProfilesService) {}

  ngOnInit(): void {
    this.profilesService.profiles.subscribe((profiles: Profile[]) => {
      this.profiles = profiles;
    });
  }

  toggleVisible() {
    this.visible = !this.visible;
  }
}

<nz-drawer [nzClosable]="false" [nzVisible]="visible" [nzWidth]="500" [nzMaskClosable]="true" nzPlacement="right"
  (nzOnClose)="toggleVisible()">
  <ng-container *nzDrawerContent>
    <nz-list nzItemLayout="horizontal">
      <nz-list-item *ngFor="let profile of profiles">
        <div>
          <span style="margin-right: 10px">{{ profile.name }}</span>
          <ng-container [ngTemplateOutlet]="actionTemplate" [ngTemplateOutletContext]="{$implicit: profile}">
          </ng-container>
        </div>
      </nz-list-item>
    </nz-list>
  </ng-container>
</nz-drawer>

<nz-affix style="position: absolute; right: 10px; bottom: 20px">
  <button nz-button nzType="primary" nzShape="circle" (click)="toggleVisible()">
    <i nz-icon nzType="user" nzTheme="outline"></i>
  </button>
</nz-affix>
