// rdc-client-react/src/pages/Session/Controller.tsx
import React, { FC, useCallback, useEffect, useRef, useState } from 'react';
import { Button } from 'antd';
import { FullscreenOutlined, FullscreenExitOutlined } from '@ant-design/icons';
import { useThrottleFn } from 'react-use';
import { useEngines } from '../../hooks/engines';

export interface ControllerProps {
  userId: string;
  streamId: number;
}

export const Controller: FC<ControllerProps> = ({ userId, streamId }) => {
  const { rdcEngine } = useEngines();
  const attachRef = useRef<HTMLDivElement>(null);
  const [isFullscreen, setIsFullScreen] = useState<boolean>();
  const [[width, height], setSize] = useState<[number, number]>([window.innerWidth, window.innerHeight - 56]);
  const size = useThrottleFn<[number, number], [number, number]>((w, h) => [w, h], 100, [width, height]);

  const handleResize = useCallback(() => setSize([window.innerWidth, window.innerHeight - 56]), [setSize]);

  useEffect(() => {
    if (rdcEngine && attachRef && attachRef.current) {
      rdcEngine.takeControl(userId, streamId, attachRef.current);
      rdcEngine.on('rdc-fullscreen-change', (iFS) => setIsFullScreen(iFS));
    }
  }, [userId, streamId, rdcEngine, attachRef]);

  useEffect(() => {
    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, [handleResize]);

  const handleFullScreen = () => {
    if (!isFullscreen && rdcEngine && attachRef && attachRef.current) {
      rdcEngine.requestFullscreen(attachRef.current);
    }
    if (isFullscreen && rdcEngine) {
      rdcEngine.exitFullscreen();
    }
  };

  return (
    <div className="rdc-client-screen-wrap">
      <div className="rdc-screen" ref={attachRef} style={size ? { width: size[0], height: size[1] } : undefined} />
      <div className="control-bar">
        <Button
          type="primary"
          shape="circle"
          icon={isFullscreen ? <FullscreenExitOutlined /> : <FullscreenOutlined />}
          onClick={handleFullScreen}
        />
      </div>
    </div>
  );
};

// rdc-client-angular/src/app/pages/session/controller/controller.component.ts
import { Component, ElementRef, HostListener, Input, AfterViewInit, ViewChild } from '@angular/core';
import { EnginesService } from 'src/app/service/engines/engines.service';

@Component({
  selector: 'app-controller',
  templateUrl: './controller.component.html',
  styleUrls: ['./controller.component.css'],
})
export class ControllerComponent implements AfterViewInit {
  @Input('userId')
  userId!: string;

  @Input('streamId')
  streamId!: number;

  isFullscreen: boolean = false;

  @ViewChild('attachEl')
  attachRef!: ElementRef<HTMLInputElement>;

  width: string = `${window.innerWidth}px`;
  height: string = `${window.innerHeight - 56}px`;

  constructor(private enginesService: EnginesService) {}

  ngAfterViewInit(): void {
    const { rdcEngine } = this.enginesService;
    if (!rdcEngine) {
      return;
    }
    rdcEngine.takeControl(this.userId, this.streamId, this.attachRef.nativeElement);
    rdcEngine.on('rdc-fullscreen-change', this.handleFullScreenChange);
  }

  toggleFullScreen() {
    const { rdcEngine } = this.enginesService;
    if (!rdcEngine) {
      return;
    }
    if (!this.isFullscreen && rdcEngine) {
      rdcEngine.requestFullscreen(this.attachRef.nativeElement);
      return;
    }
    rdcEngine.exitFullscreen();
  }

  @HostListener('window:resize', ['$event'])
  handleResize(event: any) {
    this.height = `${event.target.innerHeight - 56}px`;
    this.width = `${event.target.innerWidth}px`;
  }

  private handleFullScreenChange(isFullscreen: boolean) {
    this.isFullscreen = isFullscreen;
  }
}

<div class="rdc-client-screen-wrap">
  <div class="rdc-screen" [ngStyle]="{height: height, width: width}" #attachEl>
  </div>
  <div class="control-bar">
    <button nz-button nzType="primary" nzShape="circle" (click)="toggleFullScreen()">
      <i nz-icon nzType="fullscreen" *ngIf="isFullscreen" nzTheme="outline"></i>
      <i nz-icon nzType="fullscreen-exit" *ngIf="!isFullscreen" nzTheme="outline"></i>
    </button>
  </div>
</div>
